FROM docker/sandbox-templates:shell

ARG ARG_HOME
RUN test -n "${ARG_HOME}" || (echo "ERROR: ARG_HOME is required!" && exit 1)
ARG ARG_USER
RUN test -n "${ARG_USER}" || (echo "ERROR: ARG_USER is required!" && exit 1)
ENV HOMEDIR=${ARG_HOME}/${ARG_USER}

USER root

RUN apt-get update ; apt-get upgrade -y
RUN apt-get install -y curl git unzip xz-utils zip libglu1-mesa gpg
RUN apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev mesa-utils

# WORKDIR ${ARG_HOME}
# RUN usermod -m -d ${HOMEDIR} agent

USER agent

ENV HOME=/home/agent
# ENV HOME=${HOMEDIR}
ENV PATH=$HOME/.local/bin:$HOME/.local/opt/flutter/bin:${HOME}/.pub-cache/bin:${HOME}/.local/opt/go/bin:$PATH

WORKDIR ${HOME}/.local/opt
ADD --unpack=true https://go.dev/dl/go1.26.0.linux-arm64.tar.gz .
RUN go version
RUN git clone -b stable https://github.com/flutter/flutter.git flutter
RUN flutter doctor
RUN dart pub global activate fvm
RUN dart pub global activate flutterfire_cli
RUN dart pub global activate intl_translation
RUN fvm install 3.41.9

#RUN curl -o- https://fnm.vercel.app/install | bash
#RUN fnm install 26

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash
RUN \. "$HOME/.nvm/nvm.sh"
RUN nvm install 26

RUN curl -fsSL https://pi.dev/install.sh | sh

ENTRYPOINT [ "pi" ]
