FROM docker/sandbox-templates:claude-code

ARG PREFIX=/home/agent/.local

USER root
RUN apt-get update ; apt-get upgrade -y
RUN apt-get install -y curl git unzip xz-utils zip libglu1-mesa gpg
RUN apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev mesa-utils
RUN npm i -g firebase-tools

USER agent
ENV PATH=${PREFIX}/opt/go/bin:${PREFIX}/opt/flutter/bin:/home/agent/.pub-cache/bin:$PATH

WORKDIR ${PREFIX}/opt
ADD --unpack=true https://go.dev/dl/go1.26.5.linux-arm64.tar.gz .
RUN go version
RUN git clone -b stable https://github.com/flutter/flutter.git flutter
RUN flutter doctor
RUN dart pub global activate fvm
RUN dart pub global activate flutterfire_cli
RUN dart pub global activate intl_translation
RUN fvm install 3.41.9
