version: 3

vars:
  IMAGE: claude:sandbox

tasks:
  claude:build:
    desc: Build Claude Docker Image
    dir: "{{.TASKFILE_DIR}}"
    preconditions:
      - sh: test -f Dockerfile.claude
        msg: Dockerfile.claude not found
    cmd: |-
      docker build -f Dockerfile.claude -t {{.IMAGE}} .

  claude:run:
    desc: Run Claude Docker Image
    dir: "{{.USER_WORKING_DIR}}"
    vars:
      ARGS: --model opus
      EXISTS:
        sh: "(sbx ls | grep {{.USER_WORKING_DIR}}) || echo ''"
    preconditions:
      - sh: test -n "$(docker image ls --format '{{.Repository}}:{{.Tag}}' {{.IMAGE}})"
        msg: Image 'claude' not found
    cmds:
      - cmd: sbx run claude -- {{.ARGS}} {{.CLI_ARGS}}
        if: '[ -n "{{.EXISTS}}" ]'
      - cmd: sbx run -t {{.IMAGE}} claude -- {{.ARGS}} {{.CLI_ARGS}}
        if: '[ -z "{{.EXISTS}}" ]'
