[general]
import = ["/Users/bbode/.config/alacritty/themes/tokyo-night-storm.toml"]

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[terminal.shell]
program = "zsh"

[window]
decorations = "full"
resize_increments = true
startup_mode = "Windowed"
option_as_alt = "Both"

[window.dimensions]
columns = 120
lines = 40

[[keyboard.bindings]]
action = "ToggleSimpleFullscreen"
key = "Return"
mods = "Alt"
