theme = "tokyonight-custom"

[editor]
auto-pairs = true
bufferline = "never"
color-modes = true
cursorline = true
line-number = "relative"
mouse = true
rulers = [80,100, 120,200]
true-color = true

[editor.statusline]
left = ["mode", "spinner", "spacer", "version-control", "file-encoding"]
center = ["file-name"]
right = ["diagnostics", "selections",  "position", "position-percentage"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
newline = "all"
space = "all"
tab = "all"

[editor.indent-guides]
render = true
skip-levels = 1

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"C-j" = ["scroll_down", "move_line_down"]
"C-k" = ["scroll_up", "move_line_up"]

[keys.normal.backspace]
q = ":q!"
s = ":w"
w = [":set auto-format false", ":w!", ":set auto-format true"]
x = ":bc!"
