[[language]]
name = "dart"
auto-format = true

[language.config.dart]
analysisExcludedFolders = ["./__work__"]
enableSdkFormatter = true
lineLength = 200
completeFunctionCalls = true
showTodos = true
enableSnippets = true
documentation = "full"

[language.debugger]
name = "dart"
transport = "stdio"
command = "flutter"
args = [ "debug_adapter" ]

[[language.debugger.templates]]
name = "debug"
request = "launch"

[[language.debugger.templates.completion]]
name = "program"
completion = "filename"
default = "lib/main.dart"

[language.debugger.templates.args]
program = "{0}"
toolArgs = ["-v", "-d", "chrome"]
sendLogsToClient = true