[[language]]
name = "env"
scope = "source.env"
file-types = ["env", ".env", ".env.local", ".env.development", ".env.production", ".env.dist", ".envrc"]
injection-regex = "env"
comment-token = "#"
indent = { tab-width = 4, unit = "\t" }
roots = []
grammar = "bash"

[[language]]
name = "yaml"
auto-format = true

[language.config.yaml]
schemastore = { enable = true }

[[language]]
name = "dart"
auto-format = true

[[grammar]]
name = "dart"
source = { git = "https://github.com/UserNobody14/tree-sitter-dart", rev = "e398400a0b785af3cf571f5a57eccab242f0cdf9" }

[language.config.dart]
analysisExcludedFolders = ["./__work__"]
enableSdkFormatter = true
lineLength = 200
completeFunctionCalls = true
showTodos = true
enableSnippets = true
updateImportsOnRename = true
documentation = "full"

[language.debugger]
name = "dart"
transport = "stdio"
command = "flutter"
args = [ "debug_adapter" ]

[[language.debugger.templates]]
name = "debug"
request = "launch"

[[language.debugger.templates.completion]]
name = "program"
completion = "filename"
default = "lib/main.dart"

[language.debugger.templates.args]
program = "{0}"
toolArgs = ["-v", "-d", "chrome"]
sendLogsToClient = true

[[language]]
name = "c-sharp"
scope = "source.csharp"
injection-regex = "c-?sharp"
file-types = ["cs"]
roots = ["sln", "csproj"]
comment-token = "//"
indent = { tab-width = 4, unit = "\t" }
auto-format = true

[language.language-server]
command = "dotnet"
args = [ "/home/balint/.local/opt/omnisharp/OmniSharp.dll", "-lsp", "-v" ]
timeout = 120

[[language]]
name = "protobuf"
auto-format = true
language-server = { command = "pls" }
# formatter = { command = "buf", args = ["format"] }
