###############################################################################
# Language Servers ############################################################
###############################################################################

[language-server.my-omnisharp]
command = "dotnet"
args = [ "/home/balint/.local/opt/omnisharp/OmniSharp.dll", "-lsp" ]
timeout = 120

[language-server.pls]
command = "pls"

[language-server.hx-lsp]
command = "hx-lsp"

[language-server.buffer-language-server]
command = "buffer-language-server"

[language-server.scls]
command = "simple-completion-language-server"

###############################################################################
# Language Server Configurations ##############################################
###############################################################################

[language-server.dart.config.dart]
analysisExcludedFolders = ["__work__", ".work"]
enableSdkFormatter = true
lineLength = 200
completeFunctionCalls = true
showTodos = true
enableSnippets = true
updateImportsOnRename = true
documentation = "full"

[language-server.yaml-language-server.config.yaml]
schemastore = { enable = true }

[language-server.scls.config]
max_completion_items = 100           # set max completion results len for each group: words, snippets, unicode-input
feature_words = true                 # enable completion by word
feature_snippets = true              # enable snippets
snippets_first = true                # completions will return before snippets by default
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_unicode_input = false        # enable "unicode input"
feature_paths = false                # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)
[language-server.scls.environment]
RUST_LOG = "info,simple-completion-language-server=info"
LOG_FILE = "/tmp/completion.log"

###############################################################################
# Language Configurations #####################################################
###############################################################################

[[language]]
name = "c-sharp"
scope = "source.csharp"
injection-regex = "c-?sharp"
file-types = ["cs"]
roots = ["sln", "csproj"]
comment-token = "//"
indent = { tab-width = 4, unit = "\t" }
auto-format = true
language-servers = [ "my-omnisharp" ]

[[grammar]]
name = "c-sharp"
source = { git = "https://github.com/tree-sitter/tree-sitter-c-sharp", rev = "d83b3c661db34fde4dcd80e79ce1653d4524998d" }

[language.debugger]
name = "netcoredbg"
transport = "stdio"
command = "netcoredbg"
args = [ "--interpreter=vscode" ]
# port-arg = "--server={}"

[[language.debugger.templates]]
name = "launch"
request = "launch"
completion = [ { name = "path to dll", completion = "filename" } ]
args = { type = "coreclr", console = "internalConsole", internalConsoleOptions = "openOnSessionStart", program = "{0}" }

[[language.debugger.templates]]
name = "attach"
request = "attach"
completion = [ "pid" ]
args = { processId = "{0}" }

[[language]]
name = "dart"
auto-format = true
language-servers = [ "dart", "hx-lsp" ]

[[grammar]]
name = "dart"
source = { git = "https://github.com/UserNobody14/tree-sitter-dart", rev = "e398400a0b785af3cf571f5a57eccab242f0cdf9" }

[language.debugger]
name = "dart"
transport = "stdio"
command = "flutter"
args = [ "debug_adapter" ]

[[language.debugger.templates]]
name = "debug"
request = "launch"

[[language.debugger.templates.completion]]
name = "program"
completion = "filename"
default = "lib/main.dart"

[language.debugger.templates.args]
program = "{0}"
toolArgs = ["-v", "-d", "chrome"]
sendLogsToClient = true

[[language]]
name = "protobuf"
auto-format = true
language-servers = [ "pls" ]
formatter = { command = "clang-format", args = [ "-style={BasedOnStyle: Chromium}" ] }

[[language]]
name = "yaml"
auto-format = true
