[[language]]
name = "dart"
auto-format = true

[language.config.dart]
enableSdkFormatter = true
lineLength = 200
completeFunctionCalls = true
showTodos = true
enableSnippets = true
documentation = "full"

[language.debugger]
name = "dart"
transport = "stdio"
command = "flutter"
args = [ "debug_adapter" ]

[[language.debugger.templates]]
name = "debug"
request = "launch"
completion = [ { name = "program", completion = "filename", default = "lib/main.dart" } ]
args = { program = "{0}", console = "internalTerminal" }
